# Site settings
title: SoaH (Woaaaah!)
email: sikian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SoaH's homepage, with general rubbish to fill up busy minds.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://soah.cat" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  sikian

# Build settings
markdown: kramdown
